name: hoge#hoge
run-name: Context Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check context (unquoted)
        run: echo ${{ github.workflow }}
      - name: Check context (quoted)
        run: echo "${{ github.workflow }}"
      - name: Echo Event Name
        run: echo "${{ github.event_name }}"
      - name: Echo Event
        run: echo "${{ toJson(github.event) }}"
